imports:
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    secret: S0ME_SECRET
    templating:
        engines: ['twig']
    profiler: { only_exceptions: false }
    form:
        enabled: true
    validation:
        enabled: true
    translator:
        fallback: es
    session: ~
    assets: ~

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: WARNING
            handler: file
            channels: ["!event"]
        syslog:
            type: stream
#            level: ERROR
            level: DEBUG
            channels: ["!event"]
        file:
            type: stream
            level: debug
            channels: ["!event"]
