imports:
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    secret: S0ME_SECRET
    templating:
        engines: ['twig']
    profiler: { only_exceptions: false }
    form:
        enabled: true
    validation:  { enable_annotations: true }
    translator:  { fallbacks: ["es"] }
    session: ~
    assets: ~
    default_locale:  es
    serializer: ~

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: WARNING
            handler: file
            channels: ["!event"]
        syslog:
            type: stream
#            level: ERROR
            level: DEBUG
            channels: ["!event"]
        file:
            type: stream
            level: debug
            channels: ["!event"]

twig:
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    strict_variables: '%kernel.debug%'
