security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        User\User: plaintext

    providers:
        user:
            id: repository.user

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            pattern: ^/
            provider: user
#            anonymous: ~
            http_basic: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }