services:
    logger.dbal:
        class: Symfony\Bridge\Doctrine\Logger\DbalLogger
        public: false
        autowire: true

    database.configuration:
        class: Doctrine\DBAL\Configuration
        public: false
        calls:
            - [setSQLLogger, ["@logger.dbal"]]

    database.connection:
        class: Doctrine\DBAL\Connection
        public: false
        factory: [Doctrine\DBAL\DriverManager, getConnection]
        arguments:
            -   dbname: main
                user: root
                password: ''
                driver: pdo_sqlite
                path: '%kernel.root_dir%/../var/database/db.sqlite'
            - "@database.configuration"

    repository.user:
        class: App\Database\DbUserRepository
        autowire: true

    repository.post:
        class: App\Database\DbPostRepository
        autowire: true